# Array creation routines

## Ones and zeros

In [1]:
import numpy as np

Q1. Create a new array of 2*2 integers, without initializing entries.

A1. np.empty 함수는 배열을 생성만 하고 특정 값으로 초기화하지 않는 함수다. 이는 시간을 단축하는데 유리하다. empty 명령으로 생성된 값은 이미 지정된 값이므로 배열의 원소 값을 미리 알 수는 없다. 

In [17]:
a = np.empty([2,2], dtype = 'int32')
print(a)

[[  17301770   17695002]
 [ 611975444 1935753823]]


Q2. Let X = np.array([1,2,3], [4,5,6], np.int32). 
Create a new array with the same shape and type as X.

In [22]:
X = np.array([[1,2,3], [4,5,6]], np.int32)
np.empty([2,3], dtype = 'int32')

array([[1, 2, 3],
       [4, 5, 6]])

Q3. Create a 3-D array with ones on the diagonal and zeros elsewhere.

**np.eyes()
np.zeros()
np.ones()
np.empty()
np.identity()
np.full()** 

잘 알아두기

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Q4. Create a new array of 3*2 float numbers, filled with ones.

In [42]:
np.ones((3,2), dtype = float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Q5. Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

만약 크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 행렬을 만들고 싶다면 ones_like, zeros_like 를 쓰면 된다 

In [47]:
x = np.arange(4, dtype=np.int64)
np.ones_like(x)

array([1, 1, 1, 1], dtype=int64)

Q6. Create a new array of 3*2 float numbers, filled with zeros.

In [51]:
np.zeros((3,2), float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Q7. Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [53]:
x = np.arange(4, dtype = np.int64)
np.zeros_like(x)

array([0, 0, 0, 0], dtype=int64)

Q8. Create a new array of 2*5 uints, filled with 6.

**uint**는 부호없는 정수, u8(64비트)

**Unicode**는 유니코드 문자열, U24(24 유니코드 글자)

**Object**는 객체, O(객체에 대한 포인터)

**String**은 바이트 문자열, S24(24글자)

In [84]:
np.full((2,5),6,'uint') # or np.full((2,5),6, dtype = np.uint)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

Q9. Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

np.ones_like나 np.zeros_like와 마찬가지로 np.full_like도 가능. np.full_like()의 첫 번째 인자는 닮을 X, 두 번째 인자는 채울 요소

In [90]:
x = np.arange(4, dtype=np.int64)
np.full_like(x,6)
#or
np.ones_like(x)*6

array([6, 6, 6, 6], dtype=int64)

## From existing data

Q10. Create an array of [1, 2, 3].

In [91]:
np.array([1,2,3])

array([1, 2, 3])

Q11. Let x = [1, 2]. Convert it into an array.

In [92]:
x = [1,2]
np.array(x)

array([1, 2])

Q12. Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [107]:
X = np.array([[1,2],[3,4]])
np.matrix(X)

matrix([[1, 2],
        [3, 4]])

np.matrix(X)를 쓰는 방식 외에도 np.asarray(X)와 np.array(X)가 있다. 둘의 차이점은 원본을 어떻게 copy할 것인가의 문제다. 

np.array()의 경우 원본의 copy본을 만드는 것이기 때문에 원본이 변경되도 np.array()는 바뀌지 않는다.

하지만 np.asarray()는 참조본을 생성하는 것이기 때문에 **원본 값이 변경되면 같이 변경된다**

In [106]:
X = np.array([[1, 2], [3, 4]])
A = np.asarray(X)
B = np.array(X)
X[0,0] = 2
print('X = {}, \n A = {}, \n B={}'.format(X,A,B))

X = [[2 2]
 [3 4]], 
 A = [[2 2]
 [3 4]], 
 B=[[1 2]
 [3 4]]


Q13. Let x = [1, 2]. Conver it into an array of `float`.

In [108]:
x = [1, 2]
np.array(x, dtype = 'f')

array([1., 2.], dtype=float32)

np.asfarray()를 사용하면 dtype이 float인 array로 쉽게 바꿀 수 있다.

In [109]:
np.asfarray(x)

array([1., 2.])

Q14. Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [110]:
x = np.array([30])
np.asscalar(x)

30

Q15. Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [118]:
x = np.array([1, 2, 3])
p = np.array(x)
print(id(x), '\t', id(p))

2857886860912 	 2857886859952


np.array()와 np.copy()는 원본의 복사본을 만드는 것이기 때문에 id값도 다르다. 하지만 np.asarray()는 참조본을 만드는 것이기 때문에 id값은 같다

## Numerical ranges

Q16. Create an array of 2, 4, 6, 8, ..., 100.

In [125]:
np.arange(2,101,step =2) #arange(시작점, 끝점, step크기)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Q17. Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

np.linspace(시작점, 끝점(but indexing과 다르게 default값이 닫혀있는, 즉 inclusive하다.), size) 

*만약 exclusive하고 싶으면 endpoint = False로 디폴트 값을 변경해준다*

In [127]:
np.linspace(3,10, 50) 

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

Q18. Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

In [128]:
np.logspace(3,10,50, endpoint = False)

array([1.00000000e+03, 1.38038426e+03, 1.90546072e+03, 2.63026799e+03,
       3.63078055e+03, 5.01187234e+03, 6.91830971e+03, 9.54992586e+03,
       1.31825674e+04, 1.81970086e+04, 2.51188643e+04, 3.46736850e+04,
       4.78630092e+04, 6.60693448e+04, 9.12010839e+04, 1.25892541e+05,
       1.73780083e+05, 2.39883292e+05, 3.31131121e+05, 4.57088190e+05,
       6.30957344e+05, 8.70963590e+05, 1.20226443e+06, 1.65958691e+06,
       2.29086765e+06, 3.16227766e+06, 4.36515832e+06, 6.02559586e+06,
       8.31763771e+06, 1.14815362e+07, 1.58489319e+07, 2.18776162e+07,
       3.01995172e+07, 4.16869383e+07, 5.75439937e+07, 7.94328235e+07,
       1.09647820e+08, 1.51356125e+08, 2.08929613e+08, 2.88403150e+08,
       3.98107171e+08, 5.49540874e+08, 7.58577575e+08, 1.04712855e+09,
       1.44543977e+09, 1.99526231e+09, 2.75422870e+09, 3.80189396e+09,
       5.24807460e+09, 7.24435960e+09])

## Building matrices

Q19. Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

신기한 np기능들.. np.diag(X)나 np.diagnoal, np.diagflat, np.tri

In [131]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
X.diagonal()

array([ 0,  5, 10])

Q20. Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [134]:
np.diagflat([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Q21. Create an array which looks like below.
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

np.tri()함수의 경우 diagonal과 diagonal 밑의 수는 모두 1이고 나머지는 0인 triangular form을 만들 수 있다. 그리고 인자를 추가하여 그 크기를 조절할 수 있다. 음수로 갈 수록 1로 구성된 대각선이 밑으로 내려간다. 

In [158]:
np.tri(5,5,-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.]])

np.tri()와 비슷하게 np.tril()과 np.triu()함수가 있다. np.tril()은 lower triangle을 만들어주고 np.triu()는 upper triangle을 만들어준다. 

인자로는 ndrray가 들어와야하는데 가로로 긴 row vector의 경우 정사각행렬의 triangular form을 만들어준다. (정확하게 어떻게 operation 되는지는 밑의 예제를 보고 배우자)

In [167]:
np.tril(np.array([1,2,3]))

array([[1, 0, 0],
       [1, 2, 0],
       [1, 2, 3]])

In [182]:
np.tril(np.array([1,2,3,4,5,6,7,8,9]).reshape(3,-1),-1)

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

Q22. Create an array which looks like below.
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [187]:
np.tril(np.arange(1,13).reshape(4,3),-1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

Q23. Create an array which looks like below. array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [188]:
np.triu(np.arange(1,13).reshape(4,-1),-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])