# Array manipulation routines

In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.3'

Q1. Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [38]:
x = np.ones((10,10,3))
out = np.reshape(x,[-1,300])
assert np.allclose(out, np.ones((10,10,3)).reshape(300,-1))

np.allclose()함수는 두 개의 인자의 element를 compare해서 한 element라도 다른게 있으면 False를 출력한다. 이 때, 각 행렬의 요소를 비교하기 위해서는 broadcast가 가능한 두 행렬만을 비교할 수 있는데, 크기가 다르면 에러 메세지가 출력된다. 

**assert** 는 파이썬 뿐만 아니라 다른 computational language에서도 자주 쓰이는 용법으로, 디버깅할 때 용이하다. 에러 메세지를 출력하도록 함.

Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [42]:
x = np.arange(1,7).reshape(2,-1)
x.ravel() #or x.flatten()

array([1, 2, 3, 4, 5, 6])

Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

In [45]:
x = np.arange(1,7).reshape(2,-1)
x.flatten()[4]

5

Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).


전치(Transpose)를 할때는 보통 x.T를 쓰지만 np.swapaxes()함수도 용이하다. 이 함수는 2개의 axis를 서로 바꾸는 역할을 한다. 인자에 리스트를 넣어 몇 번째 axis와 몇 번째 axis를 바꿀 것인지 지정 가능하다. 

In [92]:
x = np.empty((3,4,5))
result1 = x.transpose([1,0,2])
result2 = np.swapaxes(x,1,0)
print(result1.shape == result2.shape)
np.allclose(result1, result2)  #왜 결과값이 False가 될까? np.allclose가 relative difference + absolute difference를 계산하기 때문이라고 함. 

True


False

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

In [102]:
x = np.empty((3,4))
x.T == x.swapaxes(0,1)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

**np.expand_dims(a,axis)**에서 a는 input array이고 axis는 새로운 axis를 넣고 싶은 부분을 의미한다. 

비슷한 함수로는 **np.newaxis**가 있다. np.newaxis의 경우 인덱싱으로 활용하여 추가하고 싶은 열에 insert하면 된다. 

In [12]:
x = np.empty((3,4))
out1 = np.expand_dims(x,1)
out2 = x[:,np.newaxis,:]
assert out1.shape == out2.shape
np.allclose(out1,out2)

True

Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

np.squeeze(a, axis)에서 a는 array를, axis는 삭제하고자 하는 축의 인덱스를 삽입하면 된다. 

In [20]:
x = np.empty((3,4,1))
np.squeeze(x,2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Q7. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].


**np.hstack**은 옆으로 concatenate 해줌. 비슷한 함수로는 *np.column_stack* 와 *c_[]*

**np.vstack**은 열의 방향으로 위아래로 concatenate해줌. 비슷한 함수는 *np.row_stack* 와 *r_[]*

**np.dstack** 2D array의 depth로 concatenate하는 역할. 3D로 해주는 역할

**np.concatenate(a,axis = n)** 은 위 수식을 통합적으로 실행할 수 있는 함수. axis = 0이면 vstack, axis=1이면 hstack, axis=2이면 dstack이다. 

In [48]:
x = np.arange(1,7).reshape(2,3)
y = np.arange(7,13).reshape(2,3)
a1 = np.hstack((x,y))
a2 = np.column_stack((x,y))
a3 = np.c_[x,y]
a4 = np.concatenate((x,y),axis=1)

assert np.allclose(a1,a2,a3,a4)
print(a1)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Q8. Let x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]


In [59]:
x = np.arange(1,7).reshape(2,3)
y = np.arange(7,13).reshape(2,3)
a1 = np.vstack((x,y))
a2 = np.row_stack((x,y))
a3 = np.r_[x,y]
a4 = np.concatenate((x,y), axis = 0)

assert np.allclose(a1,a2,a3,a4)
print(a4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Q8. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

In [74]:
x = np.array([1,2,3])
y = np.array([4,5,6])

a1 = np.dstack((x,y))
print(a1)

[[[1 4]
  [2 5]
  [3 6]]]


a2 = np.concatenate((x,y), axis=2) 하면 오류 나옴. 왜냐하면 x와 y의 shape을 알아야할 필요가 있는데 둘 다 (3)으로 1차원이다. 따라서 axis = 1 이나 axis =2 면 차원을 넘게 되면서 오류가 뜨는 것

Q9. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

In [84]:
x = np.arange(1,4).reshape(3,1)
y = np.arange(4,7).reshape(3,1)
a1 = np.dstack((x,y))
a2 = np.concatenate((x,y),axis=1)

x = a1
print(x)

[[[1 4]]

 [[2 5]]

 [[3 6]]]


**np.split(a, section, axis)** 는 array를 나눠주는 역할. a는 array, section은 나눠지는 구간. 여기서 section이 중요한데 만약 정수일 경우 n개의 배열로 나눈다는 뜻이고 튜플이나 리스트 같은 array일 경우 인덱스 표시 만큼 나눠준다. 

예를 들어) np.split(x,(2,4),axis = 0)의 경우 column-wise로 x(0:2), x(2:4), x(4:)만큼 나눠준다는 뜻

**np.split(axis = 0)** 은 **np.hsplit()** (column-wise)과 같고 **np.split(axis = 1)** 은 **np.vsplit()** (row-wise)과 같다 

**np.dsplit()** 은 3차원 이상의 deep matrix를 구분하는 함수

**np.array_split(x,a)** 는 x의 array를 정수 a개의 section으로 나눠주는 함수

Q10. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [17]:
x = np.arange(1,10)
a1 = np.split(x,(4,6))
a2 = np.split(x,(4,6), axis = 0) #x의 크기가 (3) 이기 때문에 axis = 0 만 가능
print(a1)
print(a2) 

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]
[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


In [24]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(3,4)
np.concatenate((a,b),axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Q11. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>
 
 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
Split it into two such that the first array looks like<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>
 
 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>
 
 [[  11.],<br/>
  [ 15.]]].<br/>  

reshape(a,b,c)처럼 축이 2이상일때 주의하자. 

In [31]:
import numpy as np
x = np.arange(16).reshape(2,2,4)
a1 = np.split(x,(3,),axis=2)   #주의해야할 점. (3)은 정수로 3이기 때문에 튜플로 나타내려면 (3,)해야함
a2 = np.dsplit(x,(3,))
print(a1)
print(a2)

[array([[[ 0,  1,  2],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [12, 13, 14]]]), array([[[ 3],
        [ 7]],

       [[11],
        [15]]])]
[array([[[ 0,  1,  2],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [12, 13, 14]]]), array([[[ 3],
        [ 7]],

       [[11],
        [15]]])]


Q12. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the second axis.

In [37]:
x = np.arange(16).reshape(4,4)
a1 = np.array_split(x,2,axis=1)
a2 = np.hsplit(x,2)
print(a1)
print(a2)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


Q13. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the first axis.

In [39]:
x = np.arange(16).reshape(4,4)
a1 = np.vsplit(x,2)
a2 = np.array_split(x,2,axis = 0)
print(a1)
print(a2)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


**np.tile(a,n)** 은 array a를 정수 n만큼 concatenate하거나, 튜플 n만큼 expansion하는 것이다.

**np.resize(a,n)** 은 array a를 copy를 만들어 size n으로 reshape하는 것이다. ***a.resize(n)*** 은 a의 copy를 만드는 것이 아닌 0을 반복하여 a를 변동시키므로 둘의 차이점을 알아두자

Q14. Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

In [47]:
x = np.array([0,1,2])
a1 = np.tile(x,(2,2))
a2 = np.resize(x,(2,6))
x.resize((2,6))
print(a1)
print(a2)
print(x)

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]
[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]
[[0 1 2 0 0 0]
 [0 0 0 0 0 0]]


Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

**np.repeat(a,n)** 은 array a에 대해 정수 n만큼 늘리는 것. axis의 default값은 flatten layer이고 axis = 0 or 1이면 축의 방향만큼 늘어난다. 
n이 정수가 아닌 array일 경우는 지정 axis의 shape를 맞추기 위해 broadcast된다. 

In [50]:
x = np.array([0,1,2])
np.repeat(x,2)

array([0, 0, 1, 1, 2, 2])

Q16. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

In [49]:
x = np.array([0,0,0,1,2,3,0,2,1,0])
np.trim_zeros(x)

array([1, 2, 3, 0, 2, 1])

Q17. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


**np.unique(a, return_index, return_inverse, return_counts)** 

In [62]:
x = np.array([2, 2, 1, 5, 4, 5, 1, 2, 3])
element, counts = np.unique(x, return_counts = True)
for e,c in zip(element, counts):
    print('element: {}, count: {}'.format(e,c))

element: 1, count: 2
element: 2, count: 3
element: 3, count: 1
element: 4, count: 1
element: 5, count: 2


Q18. Let x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

**np.fliplr()** 은 flip array into left/right direction
**np.flipud()** 은 flip array into up/down direction

In [64]:
x = np.arange(1,5).reshape(2,2)
np.fliplr(x)

array([[2, 1],
       [4, 3]])

Q19. Let x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

In [65]:
x = np.arange(1,5).reshape(2,2)
np.flipud(x)

array([[3, 4],
       [1, 2]])

Q20. Let x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

**np.rot90(a)** 는 array를 시계반대방향으로 90도 만큼 회전

In [66]:
x = np.arange(1,5).reshape(2,2)
np.rot90(x)

array([[2, 4],
       [1, 3]])

Q21 Let x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

**np.roll(a, shift, axis)** 에서 shift는 끝의 몇 개의 수 나 맨 앞으로 옮겨지는지, axis는 방향을 의미. axis의 default는 layer가 flattened되고 난 후다. 

In [72]:
x = np.arange(1,9).reshape(2,4)
print(np.roll(x,1,axis=1))
print(np.roll(x,1))

[[4 1 2 3]
 [8 5 6 7]]
[[8 1 2 3]
 [4 5 6 7]]
