## String operations

In [1]:
from __future__ import print_function
import numpy as np

In [2]:
author = "kyubyong. https://github.com/Kyubyong/numpy_exercises"

In [3]:
np.__version__

'1.11.3'

#### Numpy String Operations

- add()
- multiply(repeated char, num_repetition) : returns the string with multiple concatenation, element-wise (요소 별로)
- center(char, num, fillchar): fillchar에 의해 채워지고 char은 가운데로 이동. 비슷하게 왼쪽 정렬하려면 ljust(), 오른쪽 정렬은 rjust()
- join(insert, x): x안의 각 letter 사이에 insert 단어를 집어넣는다
- capitalize(): 첫 번째 letter가 capitalized
- title(): 각 단어의 첫 번째 letter가 capitalized
- lower()
- upper()
- split(char, separator): separator에 의해 char을 리스트로 출력
- splitlines(): '\n', '\r' 등 line boundaries에 의해 split됨
- strip(char, 'a'): 마지막과 끝 문자가 'a'면 remove 함.
- lstrip (), rstrip(): left와 right에 있는 letter를 제거함
- join(separator, char): char를 separator로 split시킴. 
- replace(input, char, replace): returns a copy of a string 인데 input의 char를 replace로 바꿈 
- decode()
- encode()
- zfill(x, width): len(x)를 width(int)만큼 넒히려 왼쪽에 0 삽입

Q1. Concatenate x1 and x2.

np.char.add(a,b) 는 string의 concatenation을 수행함. 약간 zip()이랑 비슷하게 인덱스가 같은 것끼리 ' '를 join한 형태로 묶임. <br> 만약 shape이 같지 않다면 오류난다

In [13]:
x1 = np.array(['Hello', 'Say'], dtype=np.str)
x2 = np.array([' world', ' something'], dtype=np.str)
print(np.char.add(x1,x2))

['Hello world' 'Say something']


Q2. Repeat x three time element-wise.

In [14]:
x = np.array(['Hello ', 'Say '], dtype=np.str)
np.char.multiply(x,3)

array(['Hello Hello Hello ', 'Say Say Say '], dtype='<U18')

Q3-1. Capitalize the first letter of x element-wise.<br/>
Q3-2. Lowercase x element-wise.<br/>
Q3-3. Uppercase x element-wise.<br/>
Q3-4. Swapcase x element-wise.<br/>
Q3-5. Title-case x element-wise.<br/>

np.char.swapcase(x)는 x안의 upper letter은 lower로, lower은 upper로 맞바꾸는 역할

In [15]:
x = np.array(['heLLo woRLd', 'Say sOmething'], dtype=np.str)
capitalized = np.char.capitalize(x)
lowered = np.char.lower(x)
uppered = np.char.upper(x)
swapcased = np.char.swapcase(x)
titlecased = np.char.title(x)
print("capitalized =", capitalized)
print("lowered =", lowered)
print("uppered =", uppered)
print("swapcased =", swapcased)
print("titlecased =", titlecased)

capitalized = ['Hello world' 'Say something']
lowered = ['hello world' 'say something']
uppered = ['HELLO WORLD' 'SAY SOMETHING']
swapcased = ['HEllO WOrlD' 'sAY SoMETHING']
titlecased = ['Hello World' 'Say Something']


Q4. Make the length of each element 20 and the string centered / left-justified / right-justified with paddings of `_`.

In [18]:
x = np.array(['hello world', 'say something'], dtype=np.str)
centered = np.char.center(x,20,'_')
left = np.char.ljust(x,20,'_')
right = np.char.rjust(x,20,'_')

print("centered =", centered)
print("left =", left)
print("right =", right)

centered = ['____hello world_____' '___say something____']
left = ['hello world_________' 'say something_______']
right = ['_________hello world' '_______say something']


Q5. Encode x in cp500 and decode it again.

In [21]:
x = np.array(['hello world', 'say something'], dtype=np.str)
encoded = np.char.encode(x, 'cp500')
decoded = np.char.decode(encoded, 'cp500')
print("encoded =", encoded)
print("decoded =", decoded)

encoded = [b'\x88\x85\x93\x93\x96@\xa6\x96\x99\x93\x84'
 b'\xa2\x81\xa8@\xa2\x96\x94\x85\xa3\x88\x89\x95\x87']
decoded = ['hello world' 'say something']


Q6. Insert a space between characters of x.

In [23]:
x = np.array(['hello world', 'say something'], dtype=np.str)
np.char.join(' ', x)

array(['h e l l o   w o r l d', 's a y   s o m e t h i n g'], dtype='<U25')

Q7-1. Remove the leading and trailing whitespaces of x element-wise.<br/>
Q7-2. Remove the leading whitespaces of x element-wise.<br/>
Q7-3. Remove the trailing whitespaces of x element-wise.

In [26]:
x = np.array(['   hello world   ', '\tsay something\n'], dtype=np.str)
stripped = np.char.strip(x)
lstripped = np.char.lstrip(x)
rstripped = np.char.rstrip(x)
print("stripped =", stripped)
print("lstripped =", lstripped)
print("rstripped =", rstripped)

stripped = ['hello world' 'say something']
lstripped = ['hello world   ' 'say something\n']
rstripped = ['   hello world' '\tsay something']


Q8. Split the element of x with spaces.

In [29]:
x = np.array(['Hello my name is John'], dtype=np.str)
np.char.split(x, ' ')

array([list(['Hello', 'my', 'name', 'is', 'John'])], dtype=object)

Q9. Split the element of x to multiple lines.

In [36]:
x = np.array(['Hello\nmy name is John'], dtype=np.str)
np.char.splitlines(x) #splitlines는 boundaries 를 다 제거함.

array([list(['Hello', 'my name is John'])], dtype=object)

Q10. Make x a numeric string of 4 digits with zeros on its left.

In [38]:
x = np.array(['34'], dtype=np.str)
np.char.zfill(x, 4)

array(['0034'], dtype='<U4')

Q11. Replace "John" with "Jim" in x.

In [39]:
x = np.array(['Hello nmy name is John'], dtype=np.str)
np.char.replace(x, 'John', 'Jim')

array(['Hello nmy name is Jim'], dtype='<U21')

## Comparison

- equal(x1,x2)
- not_equal(x1,x2)
- greater_equal(x1, x2)
- less_equal(x1, x2)
- greater(x1, x2)
- less(x1, x2)

Q12. Return x1 == x2, element-wise.

In [42]:
x1 = np.array(['Hello', 'my', 'name', 'is', 'John'], dtype=np.str)
x2 = np.array(['Hello', 'my', 'name', 'is', 'Jim'], dtype=np.str)
np.char.equal(x1,x2)

array([ True,  True,  True,  True, False])

Q13. Return x1 != x2, element-wise.

In [43]:
x1 = np.array(['Hello', 'my', 'name', 'is', 'John'], dtype=np.str)
x2 = np.array(['Hello', 'my', 'name', 'is', 'Jim'], dtype=np.str)
np.char.not_equal(x1,x2)

array([False, False, False, False,  True])

## String information

- count(a,sub, start,end): start에서 end까지(end 포함 안 함, 열려있음) a에 sub이 몇 개 있는지 세는 함수
- find(a,sub, start, end): sub이 발견되면 가장 lowest string을 return한다
- index(a, sub, start, end): find랑 비슷하지만, 만약 a에 sub가 없으면 ValueError를 일으킨다
- isalph(a): a가 alphabet(string)이면 True로 return
- isdecimal(a): digit이면 true로 리턴
- islower(a)
- isnumeric(a): numeric character 여부
- isspace(a): only whitespace인지 아닌지
- istitle(a): titlecased string인지 아닌지
- isupper(a)
- rfind(a,sub,start,end): highest index를 리턴함
- rindex(a, sub, start, end)
- startswith(a, prefix, start, end): prefix로 시작하는지 아닌지


Q14. Count the number of "l" in x, element-wise.

In [52]:
x = np.array(['Hello', 'my', 'name', 'is', 'Lily'], dtype=np.str)
np.char.count(x, 'i')

array([0, 0, 0, 1, 1])

Q15. Count the lowest index of "l" in x, element-wise.

In [54]:
x = np.array(['Hello', 'my', 'name', 'is', 'Lily'], dtype=np.str)
np.char.find(x,'i')

array([-1, -1, -1,  0,  1])

In [61]:
np.char.isalpha(np.array(['a','b','가, 1']))

array([ True,  True, False])

Q16-1. Check if each element of x is composed of digits only.<br/>
Q16-2. Check if each element of x is composed of lower case letters only.<br/>
Q16-3. Check if each element of x is composed of upper case letters only.

In [62]:
x = np.array(['Hello', 'I', 'am', '20', 'years', 'old'], dtype=np.str)
out1 = np.char.isdigit(x)
out2 = np.char.islower(x)
out3 = np.char.isupper(x)
print("Digits only =", out1)
print("Lower cases only =", out2)
print("Upper cases only =", out3)

Digits only = [False False False  True False False]
Lower cases only = [False False  True False  True  True]
Upper cases only = [False  True False False False False]


Q17. Check if each element of x starts with "hi".

In [64]:
x = np.array(['he', 'his', 'him', 'his'], dtype=np.str)
np.char.startswith(x, 'hi')

array([False,  True,  True,  True])